# Generated by Django 3.1.2 on 2020-11-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unknown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outageid', models.IntegerField()),
                ('shutid', models.IntegerField()),
                ('element', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('availed', models.BooleanField()),
            ],
        ),
    ]
