# Generated by Django 3.1.2 on 2020-11-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pwc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outageid', models.IntegerField()),
                ('shutid', models.IntegerField()),
                ('element', models.CharField(max_length=50)),
                ('elementid', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('availed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Unknown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outageid', models.IntegerField(null=True)),
                ('shutid', models.IntegerField()),
                ('element', models.CharField(max_length=50)),
                ('elementid', models.IntegerField(default=1)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('availed', models.BooleanField()),
            ],
        ),
    ]
