# Generated by Django 3.1.2 on 2020-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwc',
            name='outageid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='outageid',
            field=models.IntegerField(),
        ),
    ]
