# Generated by Django 3.1.2 on 2020-11-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20201116_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwc',
            name='availed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='unknown',
            name='availed',
            field=models.BooleanField(null=True),
        ),
    ]
